CREATE TABLE "usuarios" (
  "id_U" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "contraseña" varchar NOT NULL,
  "tipoCuenta" varchar NOT NULL DEFAULT 'Normal',
  "rol" varchar NOT NULL DEFAULT 'Usuario'
);

CREATE TABLE "Direcciones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_U" integer NOT NULL,
  "nombreDireccion" varchar NOT NULL,
  "calle" varchar NOT NULL,
  "nroCalle" varchar NOT NULL,
  "ciudad" varchar NOT NULL,
  "provincia" varchar NOT NULL,
  "CP" varchar NOT NULL
);

CREATE TABLE "SolicitudProfesional" (
  "id_SP" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_USP" integer NOT NULL,
  "id_Prof" integer NOT NULL,
  "matricula" varchar NOT NULL,
  "documentacion" varchar NOT NULL,
  "estado" varchar NOT NULL,
  "fechaSolicitud" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "Profesiones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "profesion" varchar UNIQUE NOT NULL
);

CREATE TABLE "Marcas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "Categorias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "Productos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" varchar NOT NULL,
  "stock" int NOT NULL,
  "precio" NUMERIC(10,2) NOT NULL,
  "precioProfesional" NUMERIC(10,2) NOT NULL,
  "id_marca" integer NOT NULL,
  "id_categoria" integer NOT NULL,
  "estado" BOOLEAN,
  "fechaVencimiento" TIMESTAMPTZ
);

CREATE TABLE "ImagenesProducto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_prod" integer NOT NULL,
  "url" varchar NOT NULL,
  "orden" int NOT NULL
);

CREATE TABLE "Ventas" (
  "nroVenta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_User" integer NOT NULL,
  "id_direccion" integer NOT NULL,
  "subtotal" NUMERIC(10,2) NOT NULL,
  "costoEnvio" NUMERIC(10,2) NOT NULL,
  "total" NUMERIC(10,2) NOT NULL,
  "metodoEnvio" varchar NOT NULL,
  "fechaVenta" TIMESTAMPTZ NOT NULL,
  "estado" varchar NOT NULL
);

CREATE TABLE "Pagos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_V" integer NOT NULL,
  "idTransaccionMP" varchar,
  "monto" NUMERIC(10,2) NOT NULL,
  "estado" varchar NOT NULL,
  "fechaPago" TIMESTAMPTZ
);

CREATE TABLE "DetalleVentas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nroVenta" integer NOT NULL,
  "id_prod" integer NOT NULL,
  "cantidad" int NOT NULL,
  "PU" NUMERIC(10,2) NOT NULL
);

CREATE TABLE "Carritos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_User" integer NOT NULL
);

CREATE TABLE "itemsCarrito" (
  "id_IC" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_C" integer NOT NULL,
  "id_prod" integer NOT NULL,
  "cantidad" int NOT NULL
);

CREATE TABLE "Favs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_U" integer NOT NULL,
  "id_prod" integer NOT NULL,
  "fechaAgregado" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "Direcciones" ADD FOREIGN KEY ("id_U") REFERENCES "usuarios" ("id_U") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SolicitudProfesional" ADD FOREIGN KEY ("user_USP") REFERENCES "usuarios" ("id_U") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SolicitudProfesional" ADD FOREIGN KEY ("id_Prof") REFERENCES "Profesiones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Productos" ADD FOREIGN KEY ("id_marca") REFERENCES "Marcas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Productos" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categorias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ImagenesProducto" ADD FOREIGN KEY ("id_prod") REFERENCES "Productos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ventas" ADD FOREIGN KEY ("id_User") REFERENCES "usuarios" ("id_U") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Ventas" ADD FOREIGN KEY ("id_direccion") REFERENCES "Direcciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Pagos" ADD FOREIGN KEY ("id_V") REFERENCES "Ventas" ("nroVenta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DetalleVentas" ADD FOREIGN KEY ("nroVenta") REFERENCES "Ventas" ("nroVenta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DetalleVentas" ADD FOREIGN KEY ("id_prod") REFERENCES "Productos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Carritos" ADD FOREIGN KEY ("id_User") REFERENCES "usuarios" ("id_U") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "itemsCarrito" ADD FOREIGN KEY ("id_C") REFERENCES "Carritos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "itemsCarrito" ADD FOREIGN KEY ("id_prod") REFERENCES "Productos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Favs" ADD FOREIGN KEY ("id_U") REFERENCES "usuarios" ("id_U") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Favs" ADD FOREIGN KEY ("id_prod") REFERENCES "Productos" ("id") DEFERRABLE INITIALLY IMMEDIATE;
